// Predefined Wednesday scenes used across the app.
export type WednesdayScene = {
  title: string;
  shortDescription: string;
  detailedDescription: string;
  mood: string;
  location: string;
  significance: string;
};

export const WEDNESDAY_SCENES: WednesdayScene[] = [
  { title: "Wednesday's Rave'N Dance", shortDescription: "An unforgettable dance that breaks the internet.", detailedDescription: "Beneath a sky of falling black confetti, Wednesday takes the floor and performs a jagged, hypnotic dance that becomes instantly iconic. Every twitch and stomp tells a story of defiance, turning a school formal into a quiet rebellion.", mood: "Hypnotic & Defiant", location: "Nevermore Academy Gymnasium", significance: "Defines Wednesday's unapologetic identity in a single dance." },
  { title: "Arrival at Nevermore Academy", shortDescription: "Wednesday steps through the gothic gates for the first time.", detailedDescription: "Mist curls around the stone arches as Wednesday walks toward Nevermore in her crisp black uniform. The academy looms ahead like a cathedral of secrets, and from the first step she signals she will not be tamed.", mood: "Ominous & Curious", location: "Nevermore Academy Gates", significance: "Marks the beginning of her journey among outcasts." },
  { title: "Wednesday Meets Enid", shortDescription: "Two opposites collide in a rainbow-and-black dorm.", detailedDescription: "Enid throws open the door to a room split in two: half neon plush, half monastic black. Their first words are a duel of personalities, and yet beneath the friction the seed of an unlikely friendship is planted.", mood: "Tense & Playful", location: "Ophelia Hall Dorm Room", significance: "Establishes the show's central friendship." },
  { title: "Poe Cup Competition", shortDescription: "A chaotic boat race across Crackstone's Crypt lake.", detailedDescription: "Sabotage, splinters, and screaming fill the air as the houses of Nevermore battle on the water. Wednesday wields cunning like an oar, steering her crew toward an unexpected victory.", mood: "Chaotic & Triumphant", location: "Crackstone's Crypt Lake", significance: "Wednesday earns grudging respect from her peers." },
  { title: "Nightshade Library Discovery", shortDescription: "A secret society's hidden chamber unveiled.", detailedDescription: "Behind a moving bookshelf, candlelight flickers over a circular chamber etched with old symbols. Wednesday steps inside, and the academy's secret history begins to peel open like a forbidden book.", mood: "Mysterious & Reverent", location: "Nevermore's Hidden Library", significance: "Unlocks the mystery of the Nightshades." },
  { title: "Gates Mansion Investigation", shortDescription: "An abandoned mansion holds the key to everything.", detailedDescription: "Dust motes drift through broken light as Wednesday and Enid creep through the Gates estate. Every painting watches, every floorboard accuses, and the past begins whispering its names.", mood: "Eerie & Suspenseful", location: "Gates Family Mansion", significance: "Reveals the bloodline behind the conspiracy." },
  { title: "Hyde Monster Revelation", shortDescription: "The monster wears a familiar face.", detailedDescription: "In a single, breath-stealing moment, the Hyde's identity is laid bare. Trust collapses, and Wednesday realizes that the closest danger has been wearing the warmest smile.", mood: "Shocking & Cold", location: "Weathervane Café Backroom", significance: "Pivotal twist that reframes the entire season." },
  { title: "Thing Saving Wednesday", shortDescription: "A loyal hand intervenes at the perfect moment.", detailedDescription: "Just as the night closes in around her, Thing scuttles into the frame — fingers flexing, defiant. Small, severed, and entirely devoted, he proves that family is not measured in limbs.", mood: "Tender & Triumphant", location: "Nevermore Grounds", significance: "Cements Thing as Wednesday's truest ally." },
  { title: "Crackstone Battle", shortDescription: "Wednesday faces an ancient evil reborn.", detailedDescription: "Lightning splits the sky over Nevermore as Crackstone rises from centuries of silence. Wednesday stands at the front of her classmates, sword in hand, the past and future colliding in a single strike.", mood: "Epic & Defiant", location: "Nevermore Quad", significance: "Climactic confrontation of the season." },
  { title: "Final Nevermore Celebration", shortDescription: "A bittersweet farewell as the term ends.", detailedDescription: "The dust settles. Students gather under a bruised sky, packing trunks and trading promises. Wednesday allows herself the rarest expression of all — the faintest, most knowing smile.", mood: "Bittersweet & Hopeful", location: "Nevermore Courtyard", significance: "Sets the stage for what comes next." },
];
